### PR TITLE
refactor: replaced system exec

### PR DESCRIPTION
**Pull request by glasswalk3r**
`lsb-release` just reads the `/etc/lsb-release` file, which is easy to parse and return the expected value.

### CODE REVIEW

**Comment by DrHyde** [comment]
This looks like a good idea, but I think the function for reading the file is in the wrong place - I think creating Devel::AssertOS::OSFeatures::lsb_release or something similar would be best, because lsb_release is not Ubuntu-specific - it's also exec()ed in Devel::AssertOS::Linux::{Devuan,RealDebian,Raspbian}.

If you've got the tuits to work on that that would be great, but otherwise I'll happily take your code and work some more on it.

**Comment by DrHyde** [comment]
Also note that `lsb_release` seems to read from `/etc/os-release` on Debian and Devuan. Given this, and that I wouldn't be surprised if other Debian derivatives read from somewhere else, shelling out to `lsb_release -i` seems to be the easiest way of making this work everywhere.

**Comment by glasswalk3r** [comment]
> This looks like a good idea, but I think the function for reading the file is in the wrong place - I think creating Devel::AssertOS::OSFeatures::lsb_release or something similar would be best, because lsb_release is not Ubuntu-specific - it's also exec()ed in Devel::AssertOS::Linux::{Devuan,RealDebian,Raspbian}.
> 
> If you've got the tuits to work on that that would be great, but otherwise I'll happily take your code and work some more on it.

Yeah, I can change that from this PR, no worries

**Comment by glasswalk3r** [comment]
> On further examination it seems that `lsb_release` reads from `/etc/os-release` on Debian and Devuan. Given this, and that I wouldn't be surprised if other Debian derivatives read from somewhere else, shelling out to `lsb_release -i` seems to be the easiest way of making this work everywhere. So unless I've got something Obviously Wrong here I think exec()ing is the best thing to do.

I think you're right. This is from a Ubuntu box:

```
alceu@temp:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
alceu@temp:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Why two files containing basically the same thing? I really don't know. But since Debian and other variants are using that, I guess is a safer bet.

I also testes a Rocky Linux box (which is a variant from Red Hat, which is kind missing in your distro):
```

NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

It is simple to change one file from the other, and I guess reading a file will be faster and more secure than doing an exec().

**Comment by glasswalk3r** [comment]
This [distro](https://github.com/chorny/Linux-Distribution/blob/master/lib/Linux/Distribution.pm) goes around this subject, but it looks like outdated.

**Comment by DrHyde** [comment]
The reason there's no Redhat detection is only that I don't use it and no-one has asked for it :-)

**Comment by DrHyde** [comment]
FWIW if you don't have easy access to them ...

```
$ ssh cpantesting-debian.local cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ ssh dev-devuan.local cat /etc/os-release
PRETTY_NAME="Devuan GNU/Linux 5 (daedalus)"
NAME="Devuan GNU/Linux"
VERSION_ID="5"
VERSION="5 (daedalus)"
VERSION_CODENAME="daedalus"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

Gotta love that inconsistent quoting!

**Comment by glasswalk3r** [comment]
> The reason there's no Redhat detection is only that I don't use it and no-one has asked for it :-)

I don't have access to RedHat, SuSe or Oracle, but Rocky Linux and Alma Linux are free versions of them.
I need to take a look at Alma, I may create another PR to add those bad boys over.

**Comment by DrHyde** [comment]
If you rebase on current master your PR should get automagically tested on Arch, real Debian, and Devuan

**Comment by glasswalk3r** [comment]
I'll need to change the test, using `S^O` to match Linux and then check for defined values of the `/etc/os-release` ID.

**Comment by DrHyde** [comment]
Yeah, testing all this reliably is a bugger. There's some tests in t/mockery.t which `local`ize `$^O` but obviously that's not enough to deal with detecting different flavours of an OS.

**Comment by glasswalk3r** [comment]
> Yeah, testing all this reliably is a bugger. There's some tests in t/mockery.t and t/failing-mockery.t which `local`ize `$^O` but obviously that's not enough to deal with detecting different flavours of an OS.
> 
> Maybe something similar that mocks /etc/os-release, using copies of known distributions' files in a new t/mock-etc/ would work - again, I'm happy to take what you've done and add that if you don't have the time to take this any further.

It should work now, since the tests are more generic and should work with any distribution that uses `/etc/os-release` (hopefully, all).
But it would be better to use mocks indeed.

**Comment by DrHyde** [comment]
Thanks! I'll make a new release shortly.

**Comment by DrHyde** [comment]
Now on its way to the CPAN as Devel-CheckOS-2.02

**Pull request merged**
